// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQeyoslJe6RI22-EMSm1If8pqRvTTiLi4',
    appId: '1:999170103500:web:34c6e91c88fdfea0364a69',
    messagingSenderId: '999170103500',
    projectId: 'moshir-65c13',
    authDomain: 'moshir-65c13.firebaseapp.com',
    storageBucket: 'moshir-65c13.firebasestorage.app',
    measurementId: 'G-KQM94GDX6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ghJVCpm1rU8nEuIKENTz8CIGDWsdzWo',
    appId: '1:999170103500:android:0928aca74e417b4e364a69',
    messagingSenderId: '999170103500',
    projectId: 'moshir-65c13',
    storageBucket: 'moshir-65c13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDczA0YOVCnEf4AHZLk-VnvJ0KvO6YpTqc',
    appId: '1:999170103500:ios:76c5b5833202684f364a69',
    messagingSenderId: '999170103500',
    projectId: 'moshir-65c13',
    storageBucket: 'moshir-65c13.firebasestorage.app',
    iosBundleId: 'com.example.testNotif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDczA0YOVCnEf4AHZLk-VnvJ0KvO6YpTqc',
    appId: '1:999170103500:ios:76c5b5833202684f364a69',
    messagingSenderId: '999170103500',
    projectId: 'moshir-65c13',
    storageBucket: 'moshir-65c13.firebasestorage.app',
    iosBundleId: 'com.example.testNotif',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQeyoslJe6RI22-EMSm1If8pqRvTTiLi4',
    appId: '1:999170103500:web:34c6e91c88fdfea0364a69',
    messagingSenderId: '999170103500',
    projectId: 'moshir-65c13',
    authDomain: 'moshir-65c13.firebaseapp.com',
    storageBucket: 'moshir-65c13.firebasestorage.app',
    measurementId: 'G-KQM94GDX6G',
  );
}
